spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: profile, email
            redirect-uri: http://localhost:5500/components/login/login.html
            authorization-grant-type: code
            client-name: Google
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
  mail:
    host: smtp.gmail.com
    port: 587
    username: dogiaphong2k4@gmail.com
    password: nqnn izye yshr trbx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  datasource:
    url: ${DBMS_CONNECTION:jdbc:postgresql://postgres-1:5432/job_website}
    driverClassName: org.postgresql.Driver
    password: ${DBMS_PASSWORD:mysecretpassword}
    username: ${DBMS_USERNAME:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8086

vapid:
  public:
    key: BH-fRSeM2e64YC2XlKHhojUusW9j7DcGRcvJ_Fk3RUpiIUUbX5Kn9yc3Gyty3-ZsVhhTy3YhG-Q5_x0he4wrRX4
  private:
    key: RKaZObV8kbP2tS-LY9-OcBRpfsJBmRfCUQhLz9Rt08c


springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
